version: "3.3"

services:
  redis_back:
    container_name: simpler_redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
  web_back:
    build: .
    container_name: simpler_backend
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    links:
      - redis_back
    restart: always
  web_front:
    container_name: simpler_frontend
    image: nginx
    volumes:
      - ./views:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    links:
      - web_back
    restart: always
