version: "3.3"

services:
  redis_back:
    container_name: simpler_redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always

  web_back:
    build: .
    container_name: simpler_backend
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    links:
      - redis_back
